name=SNMP Manager
version=1.2.1
author=Martin Rowan <martin@martinrowan.co.uk>
maintainer=Martin Rowan <martin@martinrowan.co.uk>
sentence=An SNMP Manager library to make SNMP requests to other SNMP enabled devices.
paragraph=Supporting SNMPv1 and SNMPv2c, SNMP requests can be sent (GetRequest) and their responses received (GetResponse) for various SNMP data types. Use 2.x for new projects. Existing 1.x sketches should select the latest 1.x release; 1.x remains maintained. Migrating to 2.x requires code changes.
category=Communication
url=https://github.com/shortbloke/Arduino_SNMP_Manager
architectures=*
includes=Arduino_SNMP_Manager.h
