[platformio]
default_envs = native
test_dir = tests/platformio

[env:native]
platform = platformio/native@1.2.1
test_framework = googletest
test_build_src = yes
extra_scripts = pre:tests/platformio/build_shared.py
build_flags =
    -std=gnu++17
    -g
    -I tests/native/support
    -I tests/native/stubs
    -I src

[env:native-sanitize]
extends = env:native
build_flags =
    ${env:native.build_flags}
    -O1
    -fsanitize=address,undefined
    -fno-sanitize-recover=all
    -fno-omit-frame-pointer
